# This is a basic workflow to help you get started with Actions
name: Hugo
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
