# This is a basic workflow to help you get started with Actions
name: Hugo
# on:
#   push:
#     branches: [ main ]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download build
      uses: actions/download-artifact@v3
      with:
        name: public
    - name: Upload build to s3
      run: |
        aws s3 sync . s3://$AWS_S3_BUCKET
      env:
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
