# This is a basic workflow to help you get started with Actions
name: Hugo
# on:
#   push:
#     branches: [ main ]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
      with:
        fetch-depth: 0
    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
    - name: list public dir
      run: |
        ls public
